server:
  port: 8686
spring:
  redis:
    host: redis
    port: 6379
  application:
    name: API-GATEWAY
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  cloud:
    gateway:
      routes:
        - id: ACTIVITY-MANAGER
          uri: lb://activity-manager
          predicates:
            - Path=/activity/**
          filters:
          - name: CircuitBreaker
            args:
              name: ACTIVITY-MANAGER
              fallbackUri: forward:/activityManagerFallBack
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 1
management:
  tracing:
    sampling:
      probability: 0.1
logging:
  pattern: level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
okta:
  oauth2:
    issuer: https://dev-30657164.okta.com/oauth2/default
    audience: api://default
    client-id: ${OKTA_LOGIN}
    client-secret: ${OKTA_PASSWORD}
    scopes: openid, profile, email, offline_access