apiVersion: apps/v1
kind: Deployment
metadata:
  name: res-vault-app
spec:
  selector:
    matchLabels:
      app: res-vault-app
  template:
    metadata:
      labels:
        app: res-vault-app
    spec:
      containers:
      - name: res-vault-app
        image: tanoer/resvaultservice
        ports:
        - containerPort: 8088
        resources:
            requests:
              cpu: "100m"  # Minimalna ilość CPU
              memory: "256Mi"  # Minimalna ilość pamięci
            limits:
              cpu: "500m"  # Maksymalna ilość CPU
              memory: "512Mi"  # Maksymalna ilość pamięci
        env:
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                key: eureka_service_address
                name: eureka-cm
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                key: config_url
                name: config-cm
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: hostname
                name: postgres-cm

---

apiVersion: v1
kind: Service
metadata:
  name: res-vault-svc
spec:
  selector:
    app: res-vault-app
  ports:
  - port: 80
    targetPort: 8088

